### ISSUE TITLE
UTF-8 error when using scanpy-scripts biocontainer

### ISSUE THREAD

**Issue by kmussar** [ebi-gene-expression-group/scanpy-scripts#55]
Hi, I'm working on developing cloud infrastructure to support single cell sequencing analysis and was excited to find your scripts! I'm trying to use them within the scanpy-scripts biocontainer found on quay (https://quay.io/repository/biocontainers/scanpy-scripts) and have been running into an error. 

When I type the commands: 
'scanpy filter-cells' or 'scanpy run-umap' I get the following error: 
"This programme requires a UTF-8 locale, please check your $LANG setting". 
I've seen that this is by design (https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/develop/scanpy_scripts/cmds.py) but am wondering if you would recommend a different docker container or another solution. 

Thanks, 
Kristin

**Comment by nh3** [comment]
Could you please try `PYTHONIOENCODING=utf-8 scanpy filter-cells` or `LANG=en_US.UTF-8 scanpy filter-cells`?

**Comment by kmussar** [comment]
Thanks for the suggestions. I tried them both and received similar errors related to the UTF-8 settings. I'm attaching screenshots of my error messages here. 
![error message_pythonencoding](https://user-images.githubusercontent.com/12243932/66068930-5083fa80-e503-11e9-998e-ee38578d0e89.JPG)
![error_lang=eng](https://user-images.githubusercontent.com/12243932/66068931-5083fa80-e503-11e9-8125-8306a0e337ff.JPG)

To give you a little more context, the nextflow script I've been running is: https://github.com/FredHutch/dv-cambiagrove/blob/kristin/nextflow/KM/scanpy3.nf
And the config file is: https://github.com/FredHutch/dv-cambiagrove/blob/kristin/nextflow/KM/nextflow.config

Thanks! 
Kristin

**Comment by nh3** [comment]
Thanks very much for the information. Unfortunately this is due to a limitation in python <3.7 that click doesn't like. I'll try push some changes that make the dependencies compatible with python 3.7 and let bioconda make a new container.

**Comment by nh3** [comment]
Hi @kmussar, a new built is made (0.2.4.post4--py_1) which should resolve the problem. Please let me know otherwise. Thanks for reporting!
