### ISSUE TITLE
Add harmony integration to CLI 

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/scanpy-scripts#82]
We'd like to add the harmony integration: https://scanpy.readthedocs.io/en/latest/external/scanpy.external.pp.harmony_integrate.html

This is not in a release version of Scanpy yet, think it will be in 1.5.2. @nh3 - any idea if any of the recent Scanpy updates will give me a headache in moving the CLI to that version?

**Comment by nh3** [comment]
Thanks @pinin4fjords for all the recent work which I believe has this issue covered.
