### ISSUE TITLE
scanpy-scripts-tests.sh does not exist

### ISSUE THREAD

**Issue by mathog** [ebi-gene-expression-group/scanpy-scripts#85]
The installation instructions refer to scanpy-scripts-tests.sh, which does not exist.  

There is instead scanpy-scripts-tests.bats.

**Comment by nh3** [comment]
Thanks for reporting. The test script is indeed `scanpy-scripts-tests.bats`, which requires [bats-core](https://github.com/bats-core/bats-core) to run. Will fix the README in the next release.

**Comment by nh3** [comment]
Thanks to @pinin4fjords, it's corrected in https://github.com/ebi-gene-expression-group/scanpy-scripts/commit/16f068d323506b15813eeb57f28452b8a89f791f.
