### ISSUE TITLE
n_genes in the var table

### ISSUE THREAD

**Issue by ksenia007** [ebi-gene-expression-group/scanpy-scripts#92]
This might be a naive question, but why are we assigning `n_genes` column to the `var` table? It was my understanding, that var column contains information about genes, while `obs` about the cells and summing on this axis would return `n_cells`. Is that not the case?

https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/2eefc331be98119448c5b6706363cd2d571645d2/scanpy_scripts/lib/__init__.py#L198

**Comment by nh3** [comment]
Sorry for the very late reply. It was indeed a typo and was fixed as part of a major revision in 0060803ba669bbe8623ef096b075d1294d9ed7b6. Thank you very much for reporting.
